Repository JohnRoyCabezas/ps-university-ebulletin-board, pull requests merged in 2022-12, with the labels that each got.

#141 [526][Bugfix]-001 - University announcement page scroll feature if p…
  client/src/components/ChangePassword.js
  client/src/components/ChatTextEditor.js
  client/src/components/CommentTextEditor.js
  client/src/components/EditSettingModal.js
  client/src/components/RichTextEditor.js
  client/src/components/Thread.js
  client/src/components/UserSidebar.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/AdminDepartmentPage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/CollegePage.js
  client/src/pages/DepartmentPage.js
Labels: :lady_beetle: Bugfix

#142 [527][Bugfix]-001 - Creating University name redirected on landing pa…
  client/src/pages/CreateUniversityPage.js
  client/src/pages/LoginPage.js
Labels: Frontend, :lady_beetle: Bugfix, :white_check_mark: Approved by Arden

#143 [528][Bugfix]-001 - Auto hide the sidebar base on the screen size, Au…
  client/src/components/AdminSidebar.js
  client/src/components/AnnouncementCard.js
  client/src/components/UserSidebar.js
  client/src/components/screenResize.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/AdminDepartmentPage.js
  client/src/pages/DepartmentPage.js
Labels: :mag_right: For Review, :lady_beetle: Bugfix, :white_check_mark: Approved by Arden

#136 [518][FE] UI update for announcement pages
  api/app/Http/Controllers/AnnouncementController.php
  client/src/components/AdminMessageOptions.js
  client/src/components/AdminThreadOptions.js
  client/src/components/AnnouncementCard.js
  client/src/components/ReplyBar.js
  client/src/components/RichTextEditor.js
  client/src/components/StudentMessageOptions.js
  client/src/components/Thread.js
  client/src/components/ThreadCard.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/AdminDepartmentPage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/CollegePage.js
  client/src/pages/DepartmentPage.js
Labels: :mag_right: For Review, Frontend, Design

#139 [514][FE] submit message on Enter key press
  client/src/components/ChatTextEditor.js
  client/src/components/CommentTextEditor.js
  client/src/components/RichTextEditor.js
  client/src/pages/ClassPage.js
Labels: :mag_right: For Review, Frontend, :mag: Roy is reviewing

#145 [530][FE]-001 - Update the register and edit user page add mobile number
  api/app/Http/Controllers/AnnouncementController.php
  api/app/Http/Controllers/AuthController.php
  client/src/pages/EditUserPage.js
  client/src/pages/RegisterPage.js
Labels: :mag_right: For Review, :lady_beetle: Bugfix

#144 [529][Bugfix] Thread will close after deletion
  client/src/components/AdminMessageOptions.js
  client/src/components/AnnouncementCard.js
  client/src/components/ChatOptions.js
Labels: :mag_right: For Review, Frontend, :lady_beetle: Bugfix
