Repository JohnRoyCabezas/ps-university-ebulletin-board, pull requests merged in 2022-11, with the labels that each got.

#82 [014][Bugfix] Dynamic university_id upon creating college
  api/app/Http/Controllers/CollegeController.php
  client/src/api/CollegeApi.js
  client/src/pages/CreateCollegePage.js
Labels: :lady_beetle: Bugfix, :white_check_mark: Approved By Jason

#84 [035][FE] Integrate backend api for fetching announcement threads
  api/app/Http/Controllers/ThreadController.php
  client/src/api/ThreadApi.js
  client/src/components/RichTextEditor.js
  client/src/components/Thread.js
  client/src/components/ThreadCard.js
  client/src/pages/DepartmentPage.js
Labels: Frontend, Approved, :white_check_mark: Approved By Jason

#85 [072][FE] Integration of announcement fetching on admin department page
  client/src/api/DepartmentApi.js
  client/src/pages/AdminDepartmentPage.js
Labels: Frontend, :mag: Jason is reviewing

#87 [059][Markup/BE/FE] Edit password markup, functionality in AuthCo…
  api/app/Http/Controllers/AuthController.php
  api/app/Http/Controllers/ChangepasswordController.php
  api/app/Models/Changepassword.php
  api/routes/api.php
  client/src/api/AnnouncementApi.js
  client/src/api/ChangePasswordApi.js
  client/src/api/UserApi.js
  client/src/components/ChangePassword.js
  client/src/components/SideBarPopupAdmin.js
  client/src/components/SidebarPopupUser.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, :white_check_mark: Approved by Roy

#88 [015][Bugfix] Users, colleges and departments fetch according to university
  api/app/Http/Controllers/AuthController.php
  api/app/Http/Controllers/CollegeController.php
  api/app/Http/Controllers/DepartmentController.php
  api/app/Http/Controllers/UserController.php
  api/app/Models/RoleUser.php
  api/database/migrations/2022_09_23_101906_create_users_table.php
  api/database/seeders/DatabaseSeeder.php
  client/src/api/CollegeApi.js
  client/src/api/DepartmentApi.js
  client/src/api/UserApi.js
  client/src/components/SideBarPopupAdmin.js
  client/src/components/Sidebar.js
  client/src/components/UsersTable.js
  client/src/pages/CreateClassPage.js
  client/src/pages/CreateCollegePage.js
  client/src/pages/CreateDepartmentPage.js
  client/src/pages/EditUserPage.js
  client/src/pages/RegisterPage.js
Labels: :mag_right: For Review, Backend, Frontend, :lady_beetle: Bugfix

#81 [064][FE] Integrate creating University in landing page
  api/app/Http/Controllers/UniversityController.php
  api/app/Models/University.php
  api/routes/api.php
  client/src/api/UniversityApi.js
  client/src/pages/CreateUniversityPage.js
  client/src/pages/LandingPage.js
  client/src/routes/RoutesList.js
Labels: Backend, Frontend, Design, :mag: Jason is reviewing

#90 [039][FE] Integrate backend API for CRUD functionalities of annou…
  api/app/Http/Controllers/CourseController.php
  api/app/Http/Controllers/ThreadController.php
  api/routes/api.php
  client/src/api/ThreadApi.js
  client/src/components/AdminThreadOptions.js
  client/src/components/ChangePassword.js
  client/src/components/RichTextEditor.js
  client/src/components/Thread.js
  client/src/components/ThreadCard.js
  client/src/pages/AnnouncementPage.js
Labels: :mag_right: For Review, Frontend, :white_check_mark: Approved by Arden

#91 [016][Bugfix] Styles from RichTextEditor now properly renders
  client/public/index.html
  client/src/components/AnnouncementCard.js
  client/src/components/RichTextEditor.js
  client/src/components/SideBarPopupAdmin.js
  client/src/components/Sidebar.js
  client/src/components/SidebarPopupUser.js
  client/src/components/ThreadCard.js
  client/src/index.css
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminDepartmentPage.js
  client/src/pages/ClassPage.js
Labels: :mag_right: For Review, Frontend, :lady_beetle: Bugfix

#92 [017][Bugfix][FE]-001 Make Edit and Delete icon not visible in studen…
  client/src/components/Sidebar.js
  client/src/pages/DepartmentPage.js
Labels: Frontend, :lady_beetle: Bugfix

#95 [060][BE/FE] Make announcements in AnnouncementPage autoupdate in realtime
  api/app/Events/AnnouncementUpdate.php
  api/app/Http/Controllers/AnnouncementController.php
  api/app/Http/Controllers/ChatController.php
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/ClassPage.js
Labels: :mag_right: For Review, Frontend, :white_check_mark: Approved by Roy, :white_check_mark: Approved by Arden

#97 [047][FE]-001 Integrate backend API for CRUD functionalities of annou…
  api/app/Http/Controllers/UserController.php
  api/app/Models/Department.php
  api/app/Models/University.php
  api/app/Models/User.php
  api/database/seeders/DatabaseSeeder.php
  client/src/components/AdminMessageOptions.js
  client/src/components/AdminThreadOptions.js
  client/src/components/AnnouncementCard.js
  client/src/components/SideBarPopupAdmin.js
  client/src/components/Sidebar.js
  client/src/components/SidebarPopupUser.js
  client/src/components/Thread.js
  client/src/components/ThreadCard.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/CollegePage.js
  client/src/pages/EditUserPage.js
  client/src/pages/RegisterPage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, Frontend

#103 [086][FE] announcement/chat card highlighted when threads/comment…
  client/src/components/AnnouncementCard.js
  client/src/components/ChatCard.js
  client/src/components/ChatOptions.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/AdminDepartmentPage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/ClassPage.js
  client/src/pages/CollegePage.js
  client/src/pages/DepartmentPage.js
Labels: :white_check_mark: Approved by Nilo

#105 [091][Bugfix] Stop searching if keyword is empty in ManageUsersPage search input
  api/app/Http/Controllers/UserController.php
  client/src/pages/ManageUsersPage.js
Labels: :white_check_mark: Approved by Nilo, :white_check_mark: Approved by Arden

#102 [085][FE] Implement Pusher Channels in chatComments for autoupdates
  api/app/Events/CommentUpdate.php
  api/app/Http/Controllers/CommentController.php
  client/src/components/Comments.js
Labels: :mag_right: For Review, Backend, Frontend, :white_check_mark: Approved by Arden

#94 [019][Bugfix] Update Dean's department_id when creating new Department
  api/app/Http/Controllers/DepartmentController.php
  client/src/pages/CreateClassPage.js
Labels: :mag_right: For Review, :lady_beetle: Bugfix

#106 [083][FE][BE] Integrate edit/delete class function
  api/app/Http/Controllers/CourseController.php
  client/src/api/CourseApi.js
  client/src/pages/ClassPage.js
  client/src/pages/EditClassPage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, Backend, Frontend, :white_check_mark: Approved by Roy

#108 [022][Bugfix] Fixed RichTextEditor special keys and thread character limit
  api/database/migrations/2022_09_26_020522_create_threads_table.php
  client/src/components/AnnouncementCard.js
  client/src/components/ChatCard.js
  client/src/components/CommentCard.js
  client/src/components/CommentsHeader.js
  client/src/components/ThreadCard.js
  client/src/components/ThreadsHeader.js
  client/src/index.css
Labels: :mag_right: For Review, Frontend, :lady_beetle: Bugfix

#111 [020][Bugfix]- Do not render college card in sidebar if user has n…
  api/app/Http/Controllers/UniversityController.php
  client/src/api/UniversityApi.js
  client/src/components/Sidebar.js
  client/src/components/SidebarPopupUser.js
Labels: :mag_right: For Review, Frontend

#110 [084][FE] Show number of replies for announcementCard and chatCard and display viewReplies on hover
  api/app/Events/ChatUpdate.php
  api/app/Events/CommentUpdate.php
  api/app/Http/Controllers/ChatController.php
  api/app/Http/Controllers/CommentController.php
  api/app/Models/Chat.php
  api/routes/web.php
  client/src/components/ChatCard.js
  client/src/components/ChatOptions.js
  client/src/components/ChatTextEditor.js
  client/src/components/CommentCard.js
  client/src/components/CommentOptions.js
  client/src/components/CommentTextEditor.js
  client/src/components/Comments.js
  client/src/pages/ClassPage.js
  client/src/pages/EditClassPage.js
Labels: :mag_right: For Review, Backend, Frontend, Design, :white_check_mark: Approved by Roy, :white_check_mark: Approved by Arden

#107 [081][Markup/FE] Add a pencil icon of collegeName in collegePage …
  client/src/components/BackButton.js
  client/src/components/CollegeAccordion.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/CreateClassPage.js
  client/src/pages/CreateCollegePage.js
  client/src/pages/CreateDepartmentPage.js
  client/src/pages/EditCollegePage.js
  client/src/pages/ManageUsersPage.js
Labels: :mag_right: For Review

#112 EditDepartmentPage
  api/app/Http/Controllers/DepartmentController.php
  client/src/api/DepartmentApi.js
  client/src/pages/AdminDepartmentPage.js
  client/src/pages/EditDepartmentPage.js
  client/src/routes/RoutesList.js
Labels: Backend, Frontend, :white_check_mark: Approved by Arden

#113 [087][FE]-001 The user can select their own theme color
  api/app/Http/Controllers/ChangepasswordController.php
  api/database/migrations/2022_09_23_101906_create_users_table.php
  api/routes/api.php
  client/src/App.js
  client/src/api/ChangePasswordApi.js
  client/src/components/AnnouncementCard.js
  client/src/components/ChangePassword.js
  client/src/components/CollegeAccordion.js
  client/src/components/Course.js
  client/src/components/DeleteModal.js
  client/src/components/DepartmentAccordion.js
  client/src/components/RichTextEditor.js
  client/src/components/SideBarPopupAdmin.js
  client/src/components/Sidebar.js
  client/src/components/SidebarPopupUser.js
  client/src/components/ThemeContext.js
  client/src/components/ThemePick.js
  client/src/components/UsersTable.js
  client/src/components/submitButton.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/AdminSettingsPage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/CollegePage.js
  client/src/pages/EditCollegePage.js
  client/src/pages/LoginPage.js
  client/src/pages/ManageUsersPage.js
  client/src/routes/RoutesList.js
  client/tailwind.config.js
Labels: :mag_right: For Review, Frontend, :white_check_mark: Approved by Roy

#115 [093][FE] Refactor code and rendering for Sidebar Component
  api/app/Events/ChatUpdate.php
  api/app/Http/Controllers/AuthController.php
  api/app/Http/Controllers/ChatController.php
  api/app/Http/Controllers/CommentController.php
  api/app/Http/Controllers/UserController.php
  api/app/Models/University.php
  api/app/Models/User.php
  client/src/api/ChatApi.js
  client/src/components/AdminSidebar.js
  client/src/components/ChangePassword.js
  client/src/components/ChatCard.js
  client/src/components/ChatTextEditor.js
  client/src/components/ClassCard.js
  client/src/components/CollegeCard.js
  client/src/components/CommentCard.js
  client/src/components/Comments.js
  client/src/components/CommentsHeader.js
  client/src/components/DepartmentCard.js
  client/src/components/EditSettingModal.js
  client/src/components/ThemePick.js
  client/src/components/UserSidebar.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/AdminDepartmentPage.js
  client/src/pages/AdminSettingsPage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/ClassPage.js
  client/src/pages/CollegePage.js
  client/src/pages/CreateClassPage.js
  client/src/pages/CreateCollegePage.js
  client/src/pages/CreateDepartmentPage.js
  client/src/pages/DepartmentPage.js
  client/src/pages/EditClassPage.js
  client/src/pages/EditCollegePage.js
  client/src/pages/EditUserPage.js
  client/src/pages/ManageUsersPage.js
  client/src/pages/RegisterPage.js
  client/src/routes/RoutesList.js
  client/src/shared/CollegeIcon.js
  client/tailwind.config.js
Labels: :mag_right: For Review, Backend, Frontend, :white_check_mark: Approved by Arden

#116 [022][Bugfix] Fix minor bugs from QA
  api/app/Models/College.php
  api/app/Models/Department.php
  api/app/Models/University.php
  client/src/components/AdminSidebar.js
  client/src/components/CollegeCard.js
  client/src/components/DepartmentCard.js
  client/src/components/UserSidebar.js
  client/src/pages/EditCollegePage.js
  client/src/pages/EditDepartmentPage.js
Labels: :lady_beetle: Bugfix

#114 [094][FE] Created modal for admin settings
  api/app/Http/Controllers/UniversityController.php
  api/routes/api.php
  client/src/api/UniversityApi.js
  client/src/components/AdminSettingsModal.js
  client/src/components/Sidebar.js
  client/src/index.css
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/AdminDepartmentPage.js
  client/src/pages/ClassPage.js
Labels: :mag_right: For Review, Frontend, :mag: Roy is reviewing

#117 [096][FE] Create class list modal for create/edit class page
  client/src/components/ClassListModal.js
  client/src/components/ClassListPicker.js
  client/src/components/DropdownMulti.js
  client/src/components/StudentCard.js
  client/src/components/ToggleSwitch.js
  client/src/index.css
  client/src/pages/CreateClassPage.js
  client/src/pages/EditClassPage.js
Labels: :mag_right: For Review, Frontend

#120 [097][FE] Highlight active card on Sidebar and fix active bugs
  api/app/Http/Controllers/ChatController.php
  client/src/components/AdminSidebar.js
  client/src/components/ChatCard.js
  client/src/components/ClassCard.js
  client/src/components/CollegeCard.js
  client/src/components/CommentCard.js
  client/src/components/Comments.js
  client/src/components/CommentsHeader.js
  client/src/components/DepartmentCard.js
  client/src/components/EditSettingModal.js
  client/src/components/UserSidebar.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/AdminDepartmentPage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/ClassPage.js
  client/src/pages/CollegePage.js
  client/src/pages/DepartmentPage.js
Labels: :mag_right: For Review, Frontend, Design, :lady_beetle: Bugfix, :white_check_mark: Approved by Arden

#122 [501][Bugfix] searching onkeypress with search debounce
  client/src/hooks/useDebounce.js
  client/src/pages/ManageUsersPage.js
Labels: :mag_right: For Review, Frontend, :lady_beetle: Bugfix, :white_check_mark: Approved by Arden

#121 [516][Bugfix] Refactor user data from cookies to react context and minor bug fixes
  api/app/Http/Controllers/UniversityController.php
  api/app/Http/Controllers/UserController.php
  client/src/App.js
  client/src/components/AdminSettingsModal.js
  client/src/components/AdminSidebar.js
  client/src/components/AnnouncementCard.js
  client/src/components/ChangePassword.js
  client/src/components/ChatCard.js
  client/src/components/ClassListPicker.js
  client/src/components/CollegeAccordion.js
  client/src/components/CommentCard.js
  client/src/components/DepartmentAccordion.js
  client/src/components/EditSettingModal.js
  client/src/components/RichTextEditor.js
  client/src/components/SideBarPopupAdmin.js
  client/src/components/Sidebar.js
  client/src/components/SidebarPopupUser.js
  client/src/components/ThemePick.js
  client/src/components/Thread.js
  client/src/components/ThreadCard.js
  client/src/components/UserSidebar.js
  client/src/components/UsersTable.js
  client/src/components/submitButton.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminSettingsPage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/ClassPage.js
  client/src/pages/CollegePage.js
  client/src/pages/CreateCollegePage.js
  client/src/pages/DepartmentPage.js
  client/src/pages/EditClassPage.js
  client/src/pages/EditCollegePage.js
  client/src/pages/LandingPage.js
  client/src/pages/ManageUsersPage.js
  client/src/routes/RoutesList.js
  client/src/routes/utilities/ProtectedRoute.js
  client/src/utils/UserContext.js
Labels: :mag_right: For Review

#123 [508][Bugfix][FE] Update University Settings Modal design
  client/src/components/AdminSettingsModal.js
  client/src/components/ClassListModal.js
Labels: :mag_right: For Review, Frontend, Design, :white_check_mark: Approved by Roy

#119 [007] User can upload file image for avatar / else set default im…
  api/app/Http/Controllers/AuthController.php
  api/app/Http/Controllers/AvatarController.php
  api/routes/api.php
  client/src/api/AvatarUploadApi.js
  client/src/api/FileInstance.js
  client/src/components/SuccessModal.js
  client/src/components/UsersTable.js
  client/src/pages/EditUserPage.js
  client/src/pages/RegisterPage.js
Labels: :mag_right: For Review, :white_check_mark: Approved by Roy

#125 [510][Bugfix]-001 - add a loading indicator on the buttons with async…
  client/src/components/AdminSettingsModal.js
  client/src/pages/EditUserPage.js
Labels: :mag_right: For Review, :white_check_mark: Approved by Arden

#124 [513][Bugfix]-001 - create a modal to view class Information - studen…
  api/app/Http/Controllers/CourseController.php
  api/app/Models/CourseUser.php
  api/app/Models/Role.php
  api/database/migrations/2022_11_21_092655_add_course_information_courses_table.php
  client/src/components/ClassListModal2.js
  client/src/components/StudentCard.js
  client/src/components/StudentCard2.js
  client/src/pages/ClassPage.js
  client/src/pages/CreateClassPage.js
  client/tailwind.config.js
Labels: :mag_right: For Review, :white_check_mark: Approved by Arden

#132 [521][Bugfix] Successful creating Class/College/Department redirects to admin settings
  client/src/components/AdminSettingsModal.js
  client/src/components/SuccessModal.js
Labels: :mag_right: For Review, :lady_beetle: Bugfix

#127 [502][Bugfix][FE] Sidebar autoupdate after edit/create/delete
  client/src/components/AdminSettingsModal.js
  client/src/components/AdminSidebar.js
  client/src/pages/CreateClassPage.js
  client/src/pages/CreateCollegePage.js
  client/src/pages/CreateDepartmentPage.js
  client/src/pages/EditClassPage.js
  client/src/pages/EditCollegePage.js
  client/src/pages/EditDepartmentPage.js
  client/src/utils/UserContext.js
Labels: :mag_right: For Review, Frontend, :lady_beetle: Bugfix

#130 [504][Bugfix][FE] Added spinner loader for page loading states
  client/src/components/LoadingSpinner.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/AdminDepartmentPage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/ClassPage.js
  client/src/pages/CollegePage.js
  client/src/pages/DepartmentPage.js
  client/src/pages/EditClassPage.js
  client/src/pages/EditCollegePage.js
  client/src/pages/EditDepartmentPage.js
  client/tailwind.config.js
Labels: :mag_right: For Review, Frontend

#131 [520][Bugfix] Add back button in all edit pages
  client/src/pages/EditClassPage.js
  client/src/pages/EditDepartmentPage.js
Labels: :mag_right: For Review, :lady_beetle: Bugfix

#134 [522][Bugfix]-001 - During the update, the upload feature is not func…
  api/app/Http/Controllers/AuthController.php
  client/src/pages/EditUserPage.js
Labels: :lady_beetle: Bugfix

#137 [524][Bugfix]-001 - Theme picker should set the radio button to check…
  client/src/components/ThemePick.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/CollegePage.js
  client/src/pages/DepartmentPage.js
Labels: :lady_beetle: Bugfix

#140 [519][Bugfix] Applied default avatar image
  client/src/pages/EditUserPage.js
  client/src/utils/UserContext.js
Labels: :mag_right: For Review, :lady_beetle: Bugfix

#133 [Bugfix]-001 Other colleges announcement reflects on other colleges
  api/app/Events/AnnouncementUpdate.php
  api/app/Http/Controllers/AnnouncementController.php
  client/src/components/AdminMessageOptions.js
  client/src/components/AnnouncementCard.js
  client/src/components/RichTextEditor.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/AdminDepartmentPage.js
  client/src/pages/CollegePage.js
  client/src/pages/DepartmentPage.js
Labels: :lady_beetle: Bugfix, :white_check_mark: Approved by Arden
