Repository JohnRoyCabezas/ps-university-ebulletin-board, pull requests merged in 2022-10, with the labels that each got.

#17 [015][BE] Add CRUD functions for Announcements in DashboardController
  api/app/Http/Controllers/DashboardController.php
  api/app/Models/Announcement.php
  api/app/Models/Announcementable.php
  api/app/Models/User.php
  api/database/migrations/2022_09_23_102608_create_announcements_table.php
  api/database/seeders/DatabaseSeeder.php
  api/routes/api.php
Labels: :mag_right: For Review, Backend, :white_check_mark: Approved by Nilo

#23 [010][FE] Integration of LoginPage
  client/src/api/AuthApi.js
  client/src/components/ErrorMessage.js
  client/src/pages/LoginPage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, Frontend, :white_check_mark: Approved by Roy, :mag: Jason is reviewing

#22 [019][Bugfix] Add dynamic input checker for register page
  client/src/pages/RegisterPage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, :lady_beetle: Bugfix, :white_check_mark: Approved by Roy

#19 [016][Markup] Create markup for Admin DashboardPage
  client/package-lock.json
  client/package.json
  client/src/components/AdminMessageOptions.js
  client/src/components/AnnouncementCard.js
  client/src/components/RichTextEditor.js
  client/src/components/StudentMessageOptions.js
  client/src/index.css
  client/src/pages/AdminAnnouncementPage.js
  client/src/routes/RoutesList.js
Labels: Frontend, :white_check_mark: Approved By Jason, :white_check_mark: Approved by Nilo

#34 [020][Markup] Create markup for Admin Settings Page
  client/src/pages/AdminSettingsPage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, Frontend

#35 [051][Bugfix] Create modal for Successful User registration
  client/src/components/RegistrationModal.js
  client/src/pages/RegisterPage.js
Labels: :mag_right: For Review, :lady_beetle: Bugfix, :white_check_mark: Approved by Roy

#44 [019][FE] Integration of announcement page (admin view)
  client/src/api/AnnouncementApi.js
  client/src/api/AuthApi.js
  client/src/components/AdminMessageOptions.js
  client/src/components/AnnouncementCard.js
  client/src/components/DeleteModal.js
  client/src/components/RichTextEditor.js
  client/src/components/StudentMessageOptions.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AnnouncementPage.js
Labels: :mag_right: For Review, Frontend

#45 [052][FE]-001 Setup Auth routes
  api/app/Http/Controllers/AuthController.php
  api/app/Models/College.php
  api/app/Models/User.php
  api/routes/api.php
  client/src/api/AuthApi.js
  client/src/components/SideBarPopup.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/LandingPage.js
  client/src/pages/LoginPage.js
  client/src/routes/RoutesList.js
Labels: Frontend, :white_check_mark: Approved by Roy

#40 [025][Markup] Create markup for Create Department Page
  client/src/pages/CreateDepartmentPage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, Frontend, :white_check_mark: Approved By Jason

#37 [023][BE] Add function to delete update and destroy user information in AuthController
  api/app/Http/Controllers/AuthController.php
  api/app/Models/Announcement.php
  api/app/Models/User.php
  api/database/migrations/2022_09_23_101906_create_users_table.php
Labels: :mag_right: For Review, Backend

#41 [028][Markup] Create markup for Create College Page
  client/src/pages/CreateCollegePage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, Frontend, :white_check_mark: Approved By Jason

#42 [031][Markup]Create markup for Create Class Page
  client/src/components/DropdownMulti.js
  client/src/pages/CreateClassPage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, Frontend, :white_check_mark: Approved By Jason

#47 [053][FE] Setup Protected Routes for Student and Admin
  client/src/components/SideBarPopup.js
  client/src/pages/ErrorPage.js
  client/src/pages/LandingPage.js
  client/src/pages/LoginPage.js
  client/src/pages/Unauthorized.js
  client/src/routes/RoutesList.js
  client/src/routes/utilities/ProtectedRoute.js
Labels: :mag_right: For Review, Frontend, :mag: Nilo is reviewing

#48 [013][BE] Add fetchThreads of announcement function to ThreadCont…
  api/app/Http/Controllers/ThreadController.php
  api/database/seeders/DatabaseSeeder.php
  api/database/seeders/ThreadSeeder.php
  api/routes/api.php
Labels: :mag_right: For Review, Backend

#38 [022][Markup] Create markup for Manage Users Page
  client/src/components/Paginate.js
  client/src/components/UsersTable.js
  client/src/pages/ManageUsersPage.js
  client/src/pages/RegisterPage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, Frontend, :mag: Jason is reviewing

#53 [040][Markup] Create markup for Edit College page
  client/src/pages/EditCollegePage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, Design

#55 [057][Markup] Create markup for Edit User Page
  client/src/pages/EditUserPage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, Design

#56 [030][FE] Integrate backend api for creating a college
  api/app/Http/Controllers/UserController.php
  api/routes/api.php
  client/src/api/CollegeApi.js
  client/src/api/UserApi.js
  client/src/components/Dropdown.js
  client/src/components/SuccessModal.js
  client/src/pages/AdminSettingsPage.js
  client/src/pages/CreateCollegePage.js
Labels: :mag_right: For Review, Frontend, :white_check_mark: Approved by Roy

#52 [026][BE] Creation of DepartmentController
  api/app/Http/Controllers/DepartmentController.php
  api/app/Models/Department.php
  api/database/migrations/2022_10_10_105537_add_column_to_departments_table.php
Labels: :mag_right: For Review, :mag: Jason is reviewing

#60 [034][FE] Integrate to sidebar all information of user
  .DS_Store
  api/app/Http/Controllers/UserController.php
  api/app/Models/University.php
  api/app/Models/User.php
  api/database/migrations/2022_10_14_053859_add_user_id_column_to_universities_table.php
  api/database/seeders/DatabaseSeeder.php
  api/routes/api.php
  client/src/api/UserApi.js
  client/src/components/CollegeAccordion.js
  client/src/components/Course.js
  client/src/components/DepartmentAccordion.js
  client/src/components/Roles.js
  client/src/components/SideBarPopup.js
  client/src/components/Sidebar.js
  client/src/index.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminSettingsPage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/CreateClassPage.js
  client/src/pages/CreateCollegePage.js
  client/src/pages/CreateDepartmentPage.js
  client/src/pages/EditCollegePage.js
  client/src/pages/EditUserPage.js
  client/src/pages/ManageUsersPage.js
  client/src/pages/RegisterPage.js
  client/src/routes/RoutesList.js
  client/src/shared/AnnouncementIcon.js
  client/src/shared/CollegeIcon.js
Labels: :mag_right: For Review, Frontend

#57 [032][BE] Creation of ClassController
  api/app/Http/Controllers/AuthController.php
  api/app/Http/Controllers/CourseController.php
  api/app/Models/Course.php
  api/app/Models/CourseUser.php
  api/database/migrations/2022_09_26_015318_create_course_users_table.php
  api/database/seeders/DatabaseSeeder.php
  api/routes/api.php
Labels: :mag_right: For Review, Backend, :mag: Jason is reviewing

#62 [058][FE] Integrate update and delete user in ManageUsersPage
  api/app/Http/Controllers/AuthController.php
  client/src/api/AuthApi.js
  client/src/components/SideBarPopup.js
  client/src/components/Sidebar.js
  client/src/components/UsersTable.js
  client/src/pages/EditUserPage.js
  client/src/pages/ManageUsersPage.js
  client/src/routes/RoutesList.js
Labels: Frontend, :white_check_mark: Approved by Roy

#59 [044][FE] Integration of Update/Delete EditCollegePage
  api/app/Http/Controllers/CollegeContoller.php
  api/app/Http/Controllers/UserController.php
  api/app/Models/College.php
  api/app/Models/RoleUser.php
  api/app/Models/University.php
  api/app/Models/User.php
  api/database/seeders/DatabaseSeeder.php
  api/routes/api.php
  client/src/api/CollegeApi.js
  client/src/api/UserApi.js
  client/src/components/DeleteModal.js
  client/src/components/SuccessModal.js
  client/src/index.js
  client/src/pages/CreateCollegePage.js
  client/src/pages/EditCollegePage.js
Labels: :mag_right: For Review, Frontend, :mag: Jason is reviewing

#61 [027][FE] Integrate backend api for creating a department
  client/src/api/CollegeApi.js
  client/src/api/DepartmentApi.js
  client/src/pages/CreateDepartmentPage.js
Labels: Approved

#63 [033][FE] Integrate backend api for creating a class and adding students
  api/app/Http/Controllers/AuthController.php
  api/app/Http/Controllers/CourseController.php
  api/app/Http/Controllers/UserController.php
  api/app/Models/CourseUser.php
  api/app/Models/User.php
  api/database/seeders/DatabaseSeeder.php
  api/routes/api.php
  client/src/api/CourseApi.js
  client/src/api/UserApi.js
  client/src/components/DepartmentAccordion.js
  client/src/components/Dropdown.js
  client/src/components/DropdownMulti.js
  client/src/components/SideBarPopupAdmin.js
  client/src/components/Sidebar.js
  client/src/components/SidebarPopupUser.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/CollegePage.js
  client/src/pages/CreateClassPage.js
  client/src/pages/CreateCollegePage.js
  client/src/pages/EditUserPage.js
  client/src/pages/RegisterPage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, Backend, Frontend

#64 [008][MU] Update Admin settings buttons centered and style button
  client/src/pages/AdminSettingsPage.js
Labels: :white_check_mark: Approved by Roy

#66 [012][Bugfix] Edit icon disappears even after RichtextEditor is closed on Ann…
  client/src/components/AdminMessageOptions.js
  client/src/components/AnnouncementCard.js
  client/src/components/DeleteModal.js
  client/src/components/RichTextEditor.js
Labels: :lady_beetle: Bugfix

#67 [011][Bugfix] Change dropdown of departments under college into a modal
  client/src/components/CollegeAccordion.js
  client/src/components/DepartmentAccordion.js
  client/src/shared/CollegeIcon.js
Labels: :mag_right: For Review, :lady_beetle: Bugfix

#69 [005][FE] Changed tab name and icon
  client/public/index.html
  client/public/mainIcon.png
Labels: :mag_right: For Review, Frontend

#68 [002][Bugfix] Announcements in Announcement Page is now ordered by creation date
  api/app/Http/Controllers/AnnouncementController.php
Labels: :mag_right: For Review, :lady_beetle: Bugfix

#71 [004][Bugfix] Update sidebar to remove bugs
  api/app/Http/Controllers/DepartmentController.php
  client/src/components/CollegeAccordion.js
  client/src/components/Sidebar.js
  client/src/components/SuccessModal.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/routes/RoutesList.js
Labels: Backend, Frontend, :lady_beetle: Bugfix, :mag: Nilo is reviewing

#74 [049][BE] Created lock functionality for announcements
  api/app/Http/Controllers/AnnouncementController.php
  api/app/Models/Announcement.php
  api/database/migrations/2022_10_25_031021_add_is_locked_column_to_announcements_table.php
  api/routes/api.php
Labels: :mag_right: For Review, Backend

#73 [013][Bugfix] Fixed sidebar component to scroll with parent colle…
  client/src/components/CollegeAccordion.js
  client/src/components/DepartmentAccordion.js
  client/src/components/Sidebar.js
Labels: :mag_right: For Review, :lady_beetle: Bugfix

#70 [065][Markup] Create markup for class page
  client/src/components/AnnouncementCard.js
  client/src/components/ChatCard.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/ClassPage.js
  client/src/pages/CollegePage.js
  client/src/routes/RoutesList.js
  client/src/shared/json/Chats.js
Labels: :mag_right: For Review, Frontend, :mag: Nilo is reviewing

#76 [050][FE] Integrate thread locking of announcements
  client/src/api/AnnouncementApi.js
  client/src/components/AnnouncementCard.js
  client/src/components/Thread.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AnnouncementPage.js
Labels: :mag_right: For Review, Frontend

#78 [062][BE] Created Controller for creating university
  api/app/Http/Controllers/UniversityController.php
  api/app/Models/University.php
  api/routes/api.php
Labels: Backend, :mag: Nilo is reviewing

#77 [001][Hotfix] Submit button Integration
  client/src/components/RichTextEditor.js
  client/src/components/submitButton.js
  client/src/pages/AdminAnnouncementPage.js
  client/src/pages/AdminSettingsPage.js
  client/src/pages/AnnouncementPage.js
  client/src/pages/CreateClassPage.js
  client/src/pages/CreateCollegePage.js
  client/src/pages/CreateDepartmentPage.js
  client/src/pages/EditCollegePage.js
  client/src/pages/RegisterPage.js
Labels: :mag_right: For Review, Hotfix

#80 [054][BE] Setup Twilio in backend
  api/.env.example
  api/app/Http/Controllers/AnnouncementController.php
  api/app/Http/Controllers/AuthController.php
  api/app/Models/User.php
  api/composer.json
  api/composer.lock
  api/database/migrations/2022_10_26_050148_add_mobile_number_to_users_table.php
Labels: :mag_right: For Review, Backend

#72 [046][BE] Create ThreadController with thread functions
  api/app/Http/Controllers/ThreadController.php
  api/app/Models/Announcement.php
  api/app/Models/Thread.php
  api/routes/api.php
  client/src/components/RichTextEditor.js
Labels: :mag_right: For Review, Backend

#83 [078][FE] Integrate ClassPage features
  api/app/Http/Controllers/ChatController.php
  api/app/Http/Controllers/CourseController.php
  api/app/Http/Controllers/UserController.php
  api/app/Models/Chat.php
  api/app/Models/Course.php
  api/app/Models/CourseUser.php
  api/app/Models/User.php
  api/database/migrations/2022_10_26_023543_create_chats_table.php
  api/routes/api.php
  client/src/api/ChatApi.js
  client/src/api/CourseApi.js
  client/src/components/ChatCard.js
  client/src/components/ChatOptions.js
  client/src/components/ChatTextEditor.js
  client/src/components/CollegeAccordion.js
  client/src/components/Course.js
  client/src/components/DepartmentAccordion.js
  client/src/components/Sidebar.js
  client/src/pages/AdminCollegePage.js
  client/src/pages/AdminDepartmentPage.js
  client/src/pages/ClassPage.js
  client/src/pages/CollegePage.js
  client/src/pages/DepartmentPage.js
  client/src/routes/RoutesList.js
Labels: :mag_right: For Review, Backend, Frontend
